### ISSUE TITLE
[Bug] D-Pad navigation selects sliders used as 'horizontal rules'

### ISSUE THREAD

**Issue by OdinVex** [Tormak9970/bash-shortcuts#10]
I'm not sure if it is intended, but you can “select” the sliders used as horizontal rules in the Bash Shortcuts “menu/overview”. Perhaps there is an alternative that could give you the same look you might be going for? Initially confused as to what was being selected, but noticed “adjust slider” near “A”, concluded it's an unintended UI-bug. Harmless, though.

**Comment by Tormak9970** [comment]
> I'm not sure if it is intended, but you can “select” the sliders used as horizontal rules in the Bash Shortcuts “menu/overview”. Perhaps there is an alternative that could give you the same look you might be going for? Initially confused as to what was being selected, but noticed “adjust slider” near “A”, concluded it's an unintended UI-bug. Harmless, though.

Bug doesnt occur in the upcoming release.
