### ISSUE TITLE
Konsole in Gaming Mode behaves differently from desktop

### ISSUE THREAD

**Issue by ThomasEricB** [Tormak9970/bash-shortcuts#11]
Konsole in Gaming Mode behaves differently from desktop in a weird way. See:
 
![image](https://user-images.githubusercontent.com/9662095/224492274-66b61d53-c7e0-4f76-999e-ab18367b5704.png)

![image](https://user-images.githubusercontent.com/9662095/224492257-e83cbbfb-a297-4d96-8047-c7251c47521a.png)

This is using @quag 's https://github.com/quag/user-nix-steam-deck Nix CHROOT script... It won't load the last line in the enter script:

[...] exec /home/deck/nix/nix-user-chroot /home/deck/nix/root-nix **~/.nix-profile/bin/bash**

This doesn't happen when launching Konsole through steam on Desktop Mode with  `konsole -e bash /home/deck/nix/enter %command%` . I have no clue why...

**Comment by ThomasEricB** [comment]
The issue is 

`/deck/nix/home/.nix-profile/bin/bash: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory `

not the LD preload

**Comment by Tormak9970** [comment]
Closing bc it was resolved on Discord

**Comment by ThomasEricB** [comment]
@Tormak9970 This is what I did to fix:

![firefox_JctQOragre](https://user-images.githubusercontent.com/9662095/224509902-529b86dc-b969-4e84-bb7b-9daab12be0f2.png)
![firefox_5s4NSk4Ooi](https://user-images.githubusercontent.com/9662095/224509906-7c6cfe36-4bf5-4346-b24c-9d097fb097b6.png)

Video: https://www.youtube.com/watch?v=sGAAOGENI48
