### ISSUE TITLE
Selected game parameters

### ISSUE THREAD

**Issue by exp111** [Tormak9970/bash-shortcuts#13]
I saw you added hooks and parameters to those.
Could you add more generic parameters like which game is selected, time, current user etc, which can be used outside of hooks?

I only wanna run some stuff on demand, which would still need game ids and such

**Comment by Tormak9970** [comment]
> I saw you added hooks and parameters to those. Could you add more generic parameters like which game is selected, time, current user etc, which can be used outside of hooks?
> 
> I only wanna run some stuff on demand, which would still need game ids and such

Time and current user for sure, that's real simple. As to selected game, do you mean like if you are on a game's page (like where you launch it from)?

**Comment by exp111** [comment]
Yeah exactly, the game page you're on. Idk how easily checkable that is. 

Maybe also the current game you're playing (decksettings has a check for that if you want a reference).

**Comment by Tormak9970** [comment]
Not worries about performance, but considering making them opt in to avoid any possible issues with conflicting flags

**Comment by Tormak9970** [comment]
I have added date, time, current user's username, current game's appId, and current game's name to general flags. Marking this as complete
