### ISSUE TITLE
[Testing Store, Latest Ver.] Can't use Konsole at all, any commands output "No such file or directory"

### ISSUE THREAD

**Issue by ThomasEricB** [Tormak9970/bash-shortcuts#15]
Basically title. Not working after reinstalling Bash Shortcuts and Decky.

**Comment by ManedCalico** [comment]
Not sure if this is related, but I'm getting "Error: Shortcut failed. Check the command." with the default Konsole command and anything else I try.

This is with a fresh install of the latest version 2.0.0-1

**Comment by Tormak9970** [comment]
Shoot. I'll look into it when I have time. In the meantime can yall share:
 - What SteamOS channel are you on? (stable, beta, or preview)
 - What Decky channel are you on? (stable or pre-release)

**Comment by ManedCalico** [comment]
No problem, I'm using stable for both.

**Comment by ThomasEricB** [comment]
I was in the testing store version.

**Comment by Tormak9970** [comment]
Closing this as I have fixed the issue. Need to test on additional channels, but it is working on stable now. Will release an update once all issues are resolved
