### ISSUE TITLE
Game start Hook not properly working

### ISSUE THREAD

**Issue by MNarath1** [Tormak9970/bash-shortcuts#16]
Using the Game start hook (together with the run as app toggle enabled) will fire the hook as indicated in the quick menu but not run the command its supposed to additionally said command will perpetually be marked as running and cannot be manually stopped (gives back error message if tried).
On other note the Game stop hook works fine and executes properly (also with run as app enabled).

**Comment by MNarath1** [comment]
This has been tried on stable just as a clarificatio and the command in question was a systemctl start service command to startup a custom service.

**Comment by Tormak9970** [comment]
Closing as this is now fixed. I will release an update once additional fixes are also complete
