### ISSUE TITLE
Not working in Steam preview + decky 2.10.0-pre2

### ISSUE THREAD

**Issue by cimba007** [Tormak9970/bash-shortcuts#17]
Selecting any shortcut and pressing A .. nothing happens.

Plugin config seems functional.

Same problem with decky 2.8.2

**Comment by Tormak9970** [comment]
Closing as this has been fixed. Unfortunately, due to the way Steam broke the api, I can't release the fix until preview changes come to stable, so I recommend reverting to beta once the most recent update is live if you wish to use bash shortcuts before then
