### ISSUE TITLE
REQ: Way to launch shortcuts via ssh

### ISSUE THREAD

**Issue by notimp** [Tormak9970/bash-shortcuts#2]
I'm looking for a way to launch a certain program (Kodi) via ssh in game mode (preferably without having to click on anything in the game mode UI first) - bash shortcuts seems like it has all of the implementation I'd need for that baked in already, but is there a way to trigger the launch of a "bash shortcut" via command line?

If so - can you please document/specify it?

if not - can you please consider adding it?

*Fingers crossed* that you implemented it in the prototyping/testing stages already. :)

Thank you for your time,

n.

**Comment by Tormak9970** [comment]
Hey, appreciate the interest. Just a heads up, bash shortcuts is a bit broken right now because of changes valve made recently. Should be fixed soon.

As to your question, if I understand correctly, you are asking if you could launch a shortcut u make with the plugin from outside of steamOS?

**Comment by notimp** [comment]
> Hey, appreciate the interest. Just a heads up, bash shortcuts is a bit broken right now because of changes valve made recently. Should be fixed soon.
> 
> As to your question, if I understand correctly, you are asking if you could launch a shortcut u make with the plugin from outside of steamOS?

Correct - or as as simple inquiry, a way of realizing "launching apps from commandline" directly - I got the feedback, that doing that via the normal linux means (defining the screen, then launching the app, or trying to launch it via wayland and environmental variables) didnt work for one person more knowledgable than be - when they tried.

So since launching apps is in the wheelhause of bash-shortcuts, I though I might ask here.

Just out of the blue. :) If there are limitations, like the steamos overlay in game mode having to be open for bash-shortcuts to be even addressable, I'm willfully unaware. :)

Just thought that you might be a person I can ask, because you already solved the entire "launching programs in game mode" through a bash command scenario. :)

My goal would be to be able to launch a program on the steamdeck in game mode via ssh (bash).

**Comment by Tormak9970** [comment]
> > Hey, appreciate the interest. Just a heads up, bash shortcuts is a bit broken right now because of changes valve made recently. Should be fixed soon.
> > As to your question, if I understand correctly, you are asking if you could launch a shortcut u make with the plugin from outside of steamOS?
> 
> Correct - or as as simple inquiry on a way of realizing "launching apps from commandline" directly (in game mode) - I got the feedback, that doing that via the normal linux means (defining the screen, then launching the app, or trying to launch it via wayland and environmental variables) didnt work for one person more knowledgable than me - when they tried.
> 
> So since launching apps is in the wheelhouse of bash-shortcuts, I though I might ask here.
> 
> Just out of the blue. :) If there are limitations, like the steamos overlay in game mode having to be open for bash-shortcuts to even be addressable, I'm willfully unaware. :)
> 
> Just thought that you might be a person I can ask, because you already solved the entire "launching programs in game mode" through a bash command scenario. :)
> 
> My goal would be to be able to launch a program on the steamdeck in game mode via ssh (bash).

Alright. It is possible to launch an app from the command line if you have a .desktop file. ex: firefox can be launched by just typing in `firefox` into the cmd line. As to using this with bash shortcuts, the example shortcut it comes with is actually an example of this. The shortcut launches the **Konsole** app. 

I have not tested anything over ssh, but u should be able to make a script file to due that (make sure its an executable) and just have a series of commands. ex: ssh into the target, then run whatever app you are trying to do.

Does that answer your question?

**Comment by notimp** [comment]
I think it does, thank you. The person who tried launching something via ssh for me (I just brainstormed the concept, and someone else answer with a high probability answer, and the tried to qualify, that  that was the correct answer and failed, that why I cant tel from personal experience ye. :) ) tried it with a .sh script and failed.

I'll see if launching a .desktop file is a possibility and would work for what I have in mind. Might hit you up again for more info - but probably not in the short term. Thank you for walking me through the basics. :)

I'll close the issue. :)
