### ISSUE TITLE
How to manually edit the shortcuts? Where are the settings stored?

### ISSUE THREAD

**Issue by HelloThisIsFlo** [Tormak9970/bash-shortcuts#21]
Hi,

In the previous version, we could edit a json file to configure or update a shortcut. But now it seems changes to this json file are ignored, the shortcuts seem to be saved somewhere else.

Where is the new location of the shortcuts config file?

The reason I'm asking this is because I have a series of related scripts and I don't want to manually type the whole path each time in the steam deck UI. I tried to copy-paste, but I can't select text in gaming mode for some reason (or I don't know how to). So if I could edit some text file via SSH it'd be much much faster. Unfortunately, even after spending 45min looking at the code I sort of gave up 😅 The JS app calls a Python backend ... and then I lost the thread 😅 I figured it would be easier to just ask 🙂

**Comment by Tormak9970** [comment]
Appreciate you tryna solve on your own. The code is def a bit convoluted lol,byproduct of Decky using python. Decky is having all plugins migrate to using the provided Python SettingsManager, so the json file is in a new location. Iirc it should be `~/homebrew/settings/bash-shortcuts/bash-shortcuts.json`

**Comment by HelloThisIsFlo** [comment]
Thanks! 
I found the file, and editing it worked 😃

Now, unfortunately, it seems none of my shortcuts are working anymore (hadn't used them in a week or so). But I see you have a PR open on the [decky-plugin-database](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/384) repo, so I'll wait until that's in, update, and report back if I have move issues. 

For the purpose of this "issue", you've answered the question so I'll close.

Thanks a lot! 😃
