### ISSUE TITLE
Bash shortcuts not working

### ISSUE THREAD

**Issue by ohuber** [Tormak9970/bash-shortcuts#24]
Hi, I'm having issues running the bash shortcuts, not even the default konsole command works. I cheched from another computer connected through ssh to check if the process is running and they dont.
Here are the log files: 

> [Bash Shortcuts] 2023-07-14 16:44:39,645 INFO Initializing Shorcuts Plugin
> [Bash Shortcuts] 2023-07-14 16:44:39,646 INFO Shortcuts loaded from settings. Shortcuts: {"fcba1cb4-4601-45d8-b919-515d152c56ef": {"id": "fcba1cb4-4601-45d8-b919-515d152c56ef", "name": "Konsole", "cmd": "konsole", "position": 1, "isApp": true, "hooks": [], "passFlags": false}, "e08aea56-85ab-4983-ac48-e005a40367a1": {"id": "e08aea56-85ab-4983-ac48-e005a40367a1", "name": "kdeconnect", "cmd": "/usr/lib/kdeconnectd -platform offscreen 2>/dev/null", "position": 2, "isApp": false, "passFlags": false, "hooks": []}, "63e70727-7a08-4aa6-addf-9a78cc19c7e9": {"id": "63e70727-7a08-4aa6-addf-9a78cc19c7e9", "name": "top", "cmd": "top", "position": 3, "isApp": false, "passFlags": false, "hooks": []}}
> [Bash Shortcuts] 2023-07-14 16:44:39,646 INFO WebSocket port loaded from settings. Port: 5000
> [Bash Shortcuts] 2023-07-14 16:44:39,646 INFO Starting Websocket server on port 5000
> [Bash Shortcuts] 2023-07-14 16:47:46,971 INFO [front-end]: user logged in. [DEBUG INFO] username: octeeeee;
> [Bash Shortcuts] 2023-07-14 16:47:46,974 INFO [front-end]: PluginController initializing...
> [Bash Shortcuts] 2023-07-14 16:47:46,976 INFO [front-end]: Services found.
> [Bash Shortcuts] 2023-07-14 16:47:46,978 INFO [front-end]: Services initialized. Success: true
> [Bash Shortcuts] 2023-07-14 16:47:47,617 INFO [front-end]: Set currentGame to Youtube appId: 2294483146.
> [Bash Shortcuts] 2023-07-14 16:47:47,633 INFO [front-end]: Got shortcuts. [DEBUG INFO] resultsLength: 49;
> [Bash Shortcuts] 2023-07-14 16:47:47,636 INFO [front-end]: WebSocket client connecting to localhost:5000...
> [Bash Shortcuts] 2023-07-14 16:47:47,637 INFO [front-end]: WebSocket client connected to localhost:5000.
> [Bash Shortcuts] 2023-07-14 16:47:47,699 INFO [front-end]: WebSocket server opened. Event: {"isTrusted":true}
> [Bash Shortcuts] 2023-07-14 16:47:47,709 INFO [front-end]: PluginController initialized.
> [Bash Shortcuts] 2023-07-14 16:47:56,597 INFO [front-end]: Set currentGame to null.
> [Bash Shortcuts] 2023-07-14 16:48:06,907 INFO [front-end]: Got shortcuts. [DEBUG INFO] resultsLength: 49;
> [Bash Shortcuts] 2023-07-14 16:48:06,909 INFO [front-end]: Got shortcuts with desired name. [DEBUG INFO] appName: Bash Shortcuts - Instance 1; resultsLength: 0;
> [Bash Shortcuts] 2023-07-14 16:48:08,686 INFO [front-end]: Shortcut is not an app. Skipping instance shortcut creation. ShortcutId: e08aea56-85ab-4983-ac48-e005a40367a1 ShortcutName: kdeconnect
> [Bash Shortcuts] 2023-07-14 16:48:08,688 INFO [front-end]: Adding websocket listener for message type e08aea56-85ab-4983-ac48-e005a40367a1
> [Bash Shortcuts] 2023-07-14 16:48:08,690 INFO [front-end]: Registered listener for message of type: e08aea56-85ab-4983-ac48-e005a40367a1.
> [Bash Shortcuts] 2023-07-14 16:48:08,694 INFO [front-end]: Created Instance for shortcut kdeconnect
> [Bash Shortcuts] 2023-07-14 16:48:08,707 INFO [front-end]: Registering for WebSocket messages of type: e08aea56-85ab-4983-ac48-e005a40367a1...
> [Bash Shortcuts] 2023-07-14 16:48:08,709 INFO [front-end]: Registered listener for message of type: e08aea56-85ab-4983-ac48-e005a40367a1.
> [Bash Shortcuts] 2023-07-14 16:48:09,861 INFO [front-end]: Shortcut is not an app. Skipping instance shortcut creation. ShortcutId: 63e70727-7a08-4aa6-addf-9a78cc19c7e9 ShortcutName: top
> [Bash Shortcuts] 2023-07-14 16:48:09,863 INFO [front-end]: Adding websocket listener for message type 63e70727-7a08-4aa6-addf-9a78cc19c7e9
> [Bash Shortcuts] 2023-07-14 16:48:09,865 INFO [front-end]: Registered listener for message of type: 63e70727-7a08-4aa6-addf-9a78cc19c7e9.
> [Bash Shortcuts] 2023-07-14 16:48:09,868 INFO [front-end]: Created Instance for shortcut top
> [Bash Shortcuts] 2023-07-14 16:48:09,885 INFO [front-end]: Registering for WebSocket messages of type: 63e70727-7a08-4aa6-addf-9a78cc19c7e9...
> [Bash Shortcuts] 2023-07-14 16:48:09,887 INFO [front-end]: Registered listener for message of type: 63e70727-7a08-4aa6-addf-9a78cc19c7e9.
> 

> (deck@steamdeck bash-shortcuts)$ cat  server.log 
> [Server] 2023-07-14 16:47:47,633 INFO ('::1', 40630, 0, 0) connected
> [Server] 2023-07-14 16:47:47,696 INFO Handling Message
> [Server] 2023-07-14 16:47:47,696 INFO Data: Hello server from TS!
>

**Comment by Tormak9970** [comment]
is this the version on the testing store?

**Comment by ohuber** [comment]
No, it's from the default store and stable decky loader channel.

**Comment by Tormak9970** [comment]
closing in favor of #25
