### ISSUE TITLE
Bash shortcuts Not Working with Decky Loader 2.11.1

### ISSUE THREAD

**Issue by dnet890** [Tormak9970/bash-shortcuts#29]
Steam OS 3.5.7 update broke Decky Loader 2.11.1. Decky Loader was updated to 2.11.1 and sadly the bash shortcuts plugin no longer works.

**Comment by csthomas2** [comment]
Came here hoping to find a resolution as well.

**Comment by MarcBittner** [comment]
Likewise. Love the plugin would love to have it fixed

**Comment by pkoko** [comment]
encounter same issue
