### ISSUE TITLE
Which folder are  the comstomerized  scripts stored in ?

### ISSUE THREAD

**Issue by bao3** [Tormak9970/bash-shortcuts#3]
The GUI has some issue ,  I want to edit the script mannually in the desktop mode . I used " find "command ,but no lucy to find it .

**Comment by Tormak9970** [comment]
So its currently bugged (waiting for the update to go live). the way the plugin works is there isn't actually multiple scripts. If you do wish to edit it manually (may or may not fix your issue) the file with all shortcuts is located at `/home/deck/.config/bash-shortcuts/shortcuts.json`

**Comment by bao3** [comment]
> So its currently bugged (waiting for the update to go live). the way the plugin works is there isn't actually multiple scripts. If you do wish to edit it manually (may or may not fix your issue) the file with all shortcuts is located at `/home/deck/.config/bash-shortcuts/shortcuts.json`

Ok , I found it and edited it.

By the way , every time  I reboot SteamDeck, I got a toast notification `adding running shortcut failed` ,and I would get a Bash Shortcuts icon in Steam.....  My English is not so good , so I try to show you in code , like:

```
while reboot
do

BashShortcuts=BashShortcuts+1;

cout<<" adding running shortcut failed";

done

```

I have to delete the icons after it reboot

**Comment by Tormak9970** [comment]
Yea, i'm aware of the bug, sorry for any issues it has caused. It should be fixed in the upcoming update
