### ISSUE TITLE
Bash Shortcuts is missing from the Decky plug-in store

### ISSUE THREAD

**Issue by gannon345** [Tormak9970/bash-shortcuts#35]
Pretty much what the title says. Not sure what would cause this but the plug-in is no longer available. Is there an alternative method to install it?

**Comment by Tormak9970** [comment]
Due to changes with both decky and steamOS the plugin isn't working right now. I do not have time to maintain it right now, and while someone is planning to take over maintenance, they won't be able to get to it for a couple of weeks. So in the meantime the plugin has been delisted

**Comment by gannon345** [comment]
Is this something with the beta channel? It’s working on stable currently.

Either way thanks for the heads up and feel free to close this issue.

**Comment by Tormak9970** [comment]
I'm under the impression it has issues on both the latest beta and the latest stable build, but I definitely know its broken on the beta channel. I'll update this report with a notice pointing to the new maintainer's fork once they start working on it, so keep an eye out for that
