### ISSUE TITLE
Can't manage to launch firefox

### ISSUE THREAD

**Issue by FinnTheDogOnDeck** [Tormak9970/bash-shortcuts#4]
Hi, I am completely new to your plugin and I can't find a way to make it work, add to that the UI bug that force you to restart the Steam deck if you try to manage your shortcut and it becomes a painful experience :)
 
I searched a couple website that some command to run Firefox but nothing I tried worked. I really want to learn on how to use your plugin, could you help me ? If you have some free time of course.

Thanks in advance.

**Comment by Tormak9970** [comment]
I've fixed the issues but I'm waiting for the update to be approved

**Comment by FinnTheDogOnDeck** [comment]
Oy I am happy to read that.

I just followed the other issue thread and managed to access the config file to delete all the broken shortcut I made in gaming mode. Thanks you for that.

However I'd like to know which command did you use to get firefox working, apparently I am too dumb to understand what the absolute path is....

Sorry to bother you with that.

**Comment by Tormak9970** [comment]
Well, seems newest version of steamOS may have broke it again, however the command i used was simply `firefox`. Iirc the reason it may not work depends on if you dont have a .desktop in a certain directory. I think its `Deck/Applications`. The .desktop file is a shortcut for firefox

**Comment by FinnTheDogOnDeck** [comment]
I do have the . desktop but firefox.lirc ain't working. I'll try to fully uninstall and reinstall firefox.

Thanks for the help
