### ISSUE TITLE
Run command with root

### ISSUE THREAD

**Issue by hilookas** [Tormak9970/bash-shortcuts#5]
I would like to run a custom shell script with root. It has some network operation commands. Could it be possible? Thanks!

**Comment by Tormak9970** [comment]
I don't know of a way to do that atm. potentially could try by having the current user be root, but idk

**Comment by hilookas** [comment]
> I don't know of a way to do that atm. potentially could try by having the current user be root, but idk

Thanks for your reply, I'll have a try.

**Comment by aarron-lee** [comment]
You can enable passwordless sudo for the script, it's what I'm doing for ryzenadj on a different Linux distro. Do note that there are security implications for enabling this, so YMMV.

[example script](https://github.com/ShadowBlip/HandyPT/blob/af496071600d44f24bf36cdc087c18fc1b1865da/bin/configure.sh) for enabling passwordless sudo
