### ISSUE TITLE
Plugin doesn't work with different home directory name

### ISSUE THREAD

**Issue by aarron-lee** [Tormak9970/bash-shortcuts#7]
## Issue:

Currently, the bash-shortcuts plugin doesn't work on other distros because there are hard coded paths being used, specifically the `/home/deck/` path.

[example here](https://github.com/Tormak9970/bash-shortcuts/blob/0fc584f25682f3fe80f14108f839088717bcea4d/src/lib/ShortcutManager.ts#L17)

## Fix:

When trying to run this plugin on another Linux distro, simply replacing all instances of  `/home/deck/` with the appropriate home directory fixes the plugin.

I manually tested this on an Aya Neo Air Pro with ChimeraOS, where I manually updated the filepaths to point to the appropriate home directory, which was `/home/gamer/`

**Comment by Tormak9970** [comment]
Didn't think to cover alternate distros/other users. I'll add this to my next update

**Comment by Tormak9970** [comment]
This will be included in the 1.2.0 update

**Comment by aarron-lee** [comment]
thank you, i'll test it once the 1.2.0 update is released

**Comment by aarron-lee** [comment]
I can confirm that the plugin now works mostly as expected, but non-app shortcuts fail. It looks like the same problem as described in #8
