### ISSUE TITLE
[Confusion]  What Quick-Access-Menu? ???

### ISSUE THREAD

**Issue by OdinVex** [Tormak9970/bash-shortcuts#9]
I've been using KDE for quite a while, and I've never heard of any Quick Access Menu of any kind. What do you mean? I see screenshots with a button for managing shortcuts...not visible on first install or reboot. I just see the default Konsole shortcut (which also doesn't work).

**Comment by Tormak9970** [comment]
> I've been using KDE for quite a while, and I've never heard of any Quick Access Menu of any kind. What do you mean? I see screenshots with a button for managing shortcuts...not visible on first install or reboot. I just see the default Konsole shortcut (which also doesn't work).

The quick access menu is the menu on the right of the steamdeck in game mode. The current version of the plugin is broken, have fixed all of it, just need to update the readme and add a guides and settings tab to the plugin before I release it. The button isnt showing up bc the live plugin uses an outdated UI lib that's broken.

**Comment by Tormak9970** [comment]
Closing this
